using Robust.Client.AutoGenerated;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Atmos.Prototypes;
using Robust.Shared.Prototypes;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Atmos.UI;

/// <summary>
///     Client-side UI used to control a portable scrubber.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PortableScrubberWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    public Action<Gas>? ScrubberFilterGasChanged;
    public bool Active;
    public HashSet<Gas>? FilterGases = new();
    private Dictionary<Gas, Button> _filterButtons = new();

    public PortableScrubberWindow()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
        var atmosphereSystem = _entManager.System<SharedAtmosphereSystem>();
        var allGases = Enum.GetValues<Gas>();
        foreach (var value in allGases)
        {
            ProtoId<GasPrototype> gasProtoId = atmosphereSystem.GetGas(value);
            var gasName = _prototypeManager.Index(gasProtoId).Name;

            var gasButton = new Button
            {
                Name = value.ToString(),
                Text = Loc.GetString(gasName),
                ToggleMode = true,
                HorizontalExpand = true,
                Pressed = FilterGases?.Contains(value) ?? false
            };
            gasButton.OnToggled += args =>
            {
                if (args.Pressed)
                    FilterGases?.Add(value);
                else
                    FilterGases?.Remove(value);
                ScrubberFilterGasChanged?.Invoke(value);
            };
            _filterButtons.Add(value, gasButton);
            GasFiltersGrid.AddChild(gasButton);
        }
    }

    public void SetActive(bool active)
    {
        Active = active;
        ToggleStatusButton.Pressed = active;

        if (active)
        {
            ToggleStatusButton.Text = Loc.GetString("comp-portable-scrubber-ui-status-enabled");
        }
        else
        {
            ToggleStatusButton.Text = Loc.GetString("comp-portable-scrubber-ui-status-disabled");
        }
    }

    public void SetPressure(float pressure, bool isFull)
    {
        ScrubberPressureLabel.SetMarkup(Loc.GetString("comp-portable-scrubber-ui-pressure", ("pressure", Math.Round(pressure)), ("color", isFull ? "red" : "green")));
    }

    public void SetConnected(bool connected)
    {
        ScrubberConnectedLabel.SetMarkup(Loc.GetString(connected ? "comp-portable-scrubber-ui-connected" : "comp-portable-scrubber-ui-disconnected"));
    }

    public void SetFilterGases(HashSet<Gas> filterGases)
    {
        FilterGases = new HashSet<Gas>(filterGases);
        foreach (var value in Enum.GetValues<Gas>())
        {
            _filterButtons[value].Pressed = FilterGases.Contains(value);
        }
    }

    public void SetTankPressure(string? tankLabel, float pressure)
    {
        var hasTank = tankLabel != null;
        NoTankBox.Visible = !hasTank;
        ExistingTankBox.Visible = hasTank;
        if (hasTank)
        {
            TankNameLabel.Text = Loc.GetString("comp-portable-scrubber-ui-tank-label", ("label", tankLabel ?? " "));
            TankPressureLabel.SetMarkup(Loc.GetString("comp-portable-scrubber-ui-tank-pressure", ("pressure", Math.Round(pressure))));
        }
    }
}
