
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.DopplerArray;
[GenerateTypedNameReferences]
public sealed partial class DopplerArrayWindow : FancyWindow
{
    public DopplerArrayWindow()
    {
        RobustXamlLoader.Load(this);
    }

}
