
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.DopplerArray;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.DopplerArray;
[GenerateTypedNameReferences]
public sealed partial class DopplerArrayWindow : FancyWindow
{
    private uint? _index;
    public Action<uint>? OnDeleteHistory;
    public DopplerArrayWindow()
    {
        RobustXamlLoader.Load(this);

        DeleteButton.OnPressed += _ =>
        {
            if (_index is not { } index)
                return;

            OnDeleteHistory?.Invoke(index);
            // prevent total spam wiping
            RecordContainer.ClearSelected();
            _index = null;
            DeleteButton.Disabled = true;
        };

        RecordContainer.OnItemSelected += args =>
        {
            _index = (uint) args.ItemIndex;
            DeleteButton.Disabled = false;
        };
        RecordContainer.OnItemDeselected += args =>
        {
            _index = null;
            DeleteButton.Disabled = true;
        };
    }

    public void UpdateState(DopplerArrayUIState state)
    {
        RecordContainer.Clear();
        NoRecords.Visible = state.Records.Count == 0;
        foreach (TachyonRecord entry in state.Records)
        {
            var line = Loc.GetString("doppler-array-ui-record-timestamp", ("time", entry.Timestamp.ToString()));
            line = Loc.GetString("doppler-array-ui-record-epicenter", ("x", MathF.Round(entry.Coordinates.X)), ("y", MathF.Round(entry.Coordinates.Y)));
            if (entry.TheoreticalRadius > entry.FactualRadius)
            {
                line += " " + Loc.GetString("doppler-array-ui-record-factual-radius", ("factual_radius", MathF.Round(entry.FactualRadius)));
                line += " " + Loc.GetString("doppler-array-ui-record-theoretical-radius", ("theoretical_radius", MathF.Round(entry.TheoreticalRadius)));
            }
            else
            {
                line += " " + Loc.GetString("doppler-array-ui-record-radius", ("radius", MathF.Round(entry.FactualRadius)));
            }
            RecordContainer.AddItem(line);
        }

        _index = null;
    }

}
