
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Piping.Unary.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using YamlDotNet.Core.Tokens;

namespace Content.Client.Atmos.UI;

/// <summary>
///     Client-side UI used to control a portable pump.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PortablePumpWindow : FancyWindow
{
    public bool Active;
    private bool _hasTank;
    private bool _connected;
    private string _directionFormatString;
    public float MaxPressure
    {
        get => _maxPressure;
        set
        {
            _maxPressure = value;
            PumpPressureOutputInput.Value = MathF.Min(value, PumpPressureOutputInput.Value);
        }
    }
    private float _maxPressure = Atmospherics.MaxOutputPressure;
    public event Action<float>? PumpOutputPressureChanged;
    public PortablePumpWindow()
    {
        RobustXamlLoader.Load(this);

        _hasTank = false;
        _connected = false;
        _directionFormatString = "comp-portable-pump-ui-pump-direction-releasing";

        PumpPressureOutputInput.OnValueChanged += _ => SetOutputPressureButton.Disabled = false;

        SetOutputPressureButton.OnPressed += _ =>
        {
            PumpPressureOutputInput.Value = Math.Clamp(PumpPressureOutputInput.Value, 0f, _maxPressure);
            PumpOutputPressureChanged?.Invoke(PumpPressureOutputInput.Value);
            SetOutputPressureButton.Disabled = false;
        };
        UpdatePumpDirectionButton();
    }

    public void SetActive(bool active)
    {
        Active = active;
        ToggleStatusButton.Pressed = active;

        if (active)
        {
            ToggleStatusButton.Text = Loc.GetString("comp-portable-pump-ui-status-enabled");
        }
        else
        {
            ToggleStatusButton.Text = Loc.GetString("comp-portable-pump-ui-status-disabled");
        }
    }

    public void SetPressure(float pressure)
    {
        PumpPressureLabel.SetMarkup(Loc.GetString("comp-portable-pump-ui-pressure", ("pressure", Math.Round(pressure))));
    }

    public void SetConnected(bool connected)
    {
        PumpConnectedLabel.SetMarkup(Loc.GetString(connected ? "comp-portable-pump-ui-connected" : "comp-portable-scrubber-ui-disconnected"));
        UpdatePumpDirectionButton();
    }

    public void SetTankPressure(string? tankLabel, float pressure)
    {
        _hasTank = tankLabel != null;
        NoTankBox.Visible = !_hasTank;
        ExistingTankBox.Visible = _hasTank;
        if (_hasTank)
        {
            TankNameLabel.Text = Loc.GetString("comp-portable-scrubber-ui-tank-label", ("label", tankLabel ?? " "));
            TankPressureLabel.SetMarkup(Loc.GetString("comp-portable-scrubber-ui-tank-pressure", ("pressure", Math.Round(pressure))));
        }
        UpdatePumpDirectionButton();
    }

    public void SetTargetPressure(float targetPressure)
    {
        PumpPressureOutputInput.Value = targetPressure;
    }

    public void SetPumpDirection(VentPumpDirection dir)
    {
        _directionFormatString = dir == VentPumpDirection.Releasing ? "comp-portable-pump-ui-pump-direction-releasing" : "comp-portable-pump-ui-pump-direction-siphoning";
        UpdatePumpDirectionButton();
    }

    private void UpdatePumpDirectionButton()
    {
        PumpDirectionButton.Text = Loc.GetString(_directionFormatString, ("target", _hasTank ? "Tank" : "Turf"), ("internal", _connected ? "Port" : "Pump"));
    }

}
